### ISSUE TITLE
No options under AnyShortcut in the plugins tab on Mac

### ISSUE THREAD

**Issue by Rosenb90** [thomasa88/AnyShortcut#1]
Hi,
I am having an issue where no options show up under the AnyShortcut plugin on Mac. I have attached a screenshot of my issue.

Thank you for your help!
![Screen Shot 2020-08-02 at 6 04 35 PM](https://user-images.githubusercontent.com/33533060/89135445-efde9900-d4ea-11ea-936a-3dae4a43d64a.jpg)

**Comment by thomasa88** [comment]
Hi, sorry for the late reply. It seems I don't get notifications for new issues on Github for some reason..

I don't have a Mac to test on myself, so I have not been able to test the bug. Can you please try with the latest release and see if you get any error messages?

If that is the case:

1. Copy the error messages and add them here.

2. Can you try replacing AnyShortcut.py with [this version](https://raw.githubusercontent.com/thomasa88/AnyShortcut/show-paths/AnyShortcut.py), stop the add-in and then run it again. You should get a prompt that (hopefully) shows two file paths. Please include that prompt here.

It should look something like this:
![image](https://user-images.githubusercontent.com/89997/90313602-1bf81200-df0e-11ea-933d-ab5ac1795137.png)

3. The add-in tries to add the following path to the "Deploy" path. Can you see if it exists?
/Neutron/UI/Commands/Resources/Camera/LookAt

In my case, it is:
C:/Users/Thomas/AppData/Local/Autodesk/webdeploy/production/857e9b22c3aee8f76d8c95036c0e01aeea4aa86a **/Neutron/UI/Commands/Resources/Camera/LookAt**

**Comment by Rosenb90** [comment]
When I run the latest version of the script I get a new error message: 
![Screen Shot 2020-08-16 at 2 47 10 PM](https://user-images.githubusercontent.com/33533060/90342686-d7cd4600-dfcf-11ea-98af-29f6235b25b7.jpg)
I also ran the new script you gave me and got this output: 
![Screen Shot 2020-08-16 at 2 48 01 PM](https://user-images.githubusercontent.com/33533060/90342705-eb78ac80-dfcf-11ea-94e4-dc8303cf2a4f.jpg)
I checked to see if the file path you provided was present on my system. It was not.

Thanks for your help!

**Comment by thomasa88** [comment]
Thanks for checking. It is as I suspected: The icons are not in the same locations on Mac.

I have updated AnyShortcut.py once again. Can you please check the message you get when running [this file](https://raw.githubusercontent.com/thomasa88/AnyShortcut/show-paths/AnyShortcut.py)?

Would you mind searching for a folder called CheckBoxChecked in /Users/brianrosen/Library/Application/Support/Autodesk/webdeploy/production ? It should have PNG files in it, named something like 16x16.png

**Comment by Rosenb90** [comment]
here is the output from the new script:
![Screen Shot 2020-08-17 at 5 02 21 PM](https://user-images.githubusercontent.com/33533060/90448707-885c4800-e0ab-11ea-9dc6-eb11827fddaf.jpg)
I do not have any PNG files in the folder you specified.

Thanks!

**Comment by thomasa88** [comment]
Thanks. The application directories seem to be much more spread out on Mac.

I think I have fixed everything, so please try [AnyShort.py](https://github.com/thomasa88/AnyShortcut/blob/next/AnyShortcut.py) from the "next" branch :) .

**Comment by Rosenb90** [comment]
AnyShortcut.py in "next" branch works!

**Comment by thomasa88** [comment]
Great! Thanks for helping me track it down. I have created release v1.0.1.
