### ISSUE TITLE
Look at Sketch Problem 

### ISSUE THREAD

**Issue by deka552** [thomasa88/AnyShortcut#12]
Hello, I found a problem:
![Fusion 360](https://github.com/thomasa88/AnyShortcut/assets/61697892/938fbe0c-20df-4d46-a830-ad215b00a903)

**Comment by thomasa88** [comment]
Hi, please try out v1.1.2 that I just released:
https://github.com/thomasa88/AnyShortcut/releases/download/v1.1.2/AnyShortcut-v1.1.2.zip

Please confirm that it fixes the issue for you. Then I will go ahead and publish a new version in the Autodesk app store.

If you have installed using the installer from the Autodesk app store, you can replace AnyShortcut.py and AnyShortcut.manifest with the files in the zip file to test the change. You can find the installation directory by expanding Details in the add-ins dialog in Fusion 360.

**Comment by deka552** [comment]
Hi Thomas
Thanks a lot!

**Comment by thomasa88** [comment]
Version 1.1.2 has been submitted to Autodesk.
