### ISSUE TITLE
Start recording option grayed out

### ISSUE THREAD

**Issue by samesand** [thomasa88/AnyShortcut#2]
I installed Anyshortcut both using the windows installer (running WIN10) and manually from the Github repository. But the option to start recording remains grayed out. I can execute the build-in commands.

One issue that I can think of is that I have Python 3.8 installed, and I'm not sure if your add-in supports it.

Thank you for any help you can provide and for creating such a great add in. 

![image](https://user-images.githubusercontent.com/38790017/96968878-7a211280-14c6-11eb-86c1-e8fea87a1eb6.png)

**Comment by Nameveiof** [comment]
Same problem. win 10 (1809)
fusion 360 (2.0.9305)

**Comment by thomasa88** [comment]
Thanks for reporting this. It turns out that I did not have notifications enabled for this project.

I had some left-over code for configuring the icons that suddenly started working in Fusion 360 in October 2020.

Fix was published in release v 1.1.1.

Closing this issue.
